import { getCaseNavigation } from "@/lib/case-navigation";
import CasePresentation from "@/components/CasePresentation";
import { BackToPortfolio, CaseExternalLink, CaseNavigation } from "@/components/CaseStudyUI";
import FellowshipEvidence from "@/components/FellowshipEvidence";
import copy from "@/lib/fellowship-editorial.json";
import assets from "@/lib/fellowship-assets.json";
const figma="https://www.figma.com/design/amDM45xs0St1MQU40tfl0f/";
function Source({node,children="Fuente · Figma"}:{node:string;children?:React.ReactNode}) {return <a href={`${figma}?node-id=${node.replace(":","-")}`} target="_blank" rel="noopener noreferrer">{children}<span className="sr-only"> (abre en otra pestaña)</span> ↗</a>}
function Figure({name,label,caption}:{name:keyof typeof assets;label:string;caption:string}) { const a=assets[name];const id=`fl-${name}-caption`;return <figure className="fl-figure"><h3>{label}</h3><div className={`fl-preview-pan ${["wireframe01","wireframe02","diferencial"].includes(name)?"fl-wide-preview":""}`} tabIndex={0} role="region" aria-label={["procesoDesktop","formularioDesktop"].includes(name)?`Composición completa de ${label}`:`Vista de ${label}; desplazable horizontalmente en pantallas estrechas`}><FellowshipEvidence asset={a} caption={caption} describedBy={id}/></div>{["wireframe01","wireframe02","diferencial"].includes(name)&&<p className="fl-pan-hint">Desplazá la imagen lateralmente o abrila para verla completa.</p>}<figcaption id={id}>{caption} <Source node={a.node}/></figcaption></figure> }
function Prose({index,from=0,to}:{index:number;from?:number;to?:number}) {return <div className="fl-prose">{copy.sections[index].paragraphs.slice(from,to).map(p=><p key={p}>{p}</p>)}</div>}
function Heading({index}:{index:number}) {return <h2 id={`fl-heading-${index}`}>{copy.sections[index].heading}</h2>}
const wireCaption="Dos iteraciones conservadas de la apertura de Empresas: cambia la navegación y el peso de la representación de producto. Trabajé la revisión de estructura; el wireframe inicial se conserva como referencia.";
const processCaption="El mismo proceso conserva su secuencia en cuatro columnas y en una lista apilada. Diseñé la adaptación y documenté el comportamiento esperado para desarrollo.";
const formCaption="Formulario diseñado para requerimientos de talento: rol y fecha comparten fila en desktop y se apilan en mobile. El formulario pertenece a la entrega de diseño; la web publicada ofrece contacto por WhatsApp.";
export default function FellowshipCase(){ return <main id="contenido-principal" tabIndex={-1} className="case-main fellowship-case">
<header id="inicio" className="case-hero home-container"><BackToPortfolio/><div className="fl-opening-with-cover"><div className="fl-opening"><h1>{copy.title}</h1><p className="fl-intro">{copy.intro}</p><div className="case-project-links"><CaseExternalLink href="https://www.nocountry.tech/para-empresas/contratar/">Ver web publicada ↗</CaseExternalLink><CaseExternalLink href={`${figma}?node-id=166-368`}>Ver diseño de la landing Empresas ↗</CaseExternalLink></div></div><CasePresentation project="fellowship" alt="Landing Empresas de No Country: regiones de apertura desktop y mobile de mi diseño" /></div></header>
<article className="case-body home-container" aria-label="Diseño web Fellowship para No Country">
<section className="fl-context" aria-labelledby="fl-context-heading"><h2 id="fl-context-heading">Contexto y alcance</h2><dl>{copy.facts.map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl><p className="fl-scope">{copy.scope}</p></section>
<section aria-labelledby="fl-heading-0"><div className="fl-argument"><Heading index={0}/><Prose index={0}/></div></section>
<section aria-labelledby="fl-heading-1"><div className="fl-argument"><Heading index={1}/><Prose index={1} to={2}/></div>
<div className="fl-wireframes"><Figure name="wireframe01" label="Iteración 01 · apertura" caption={wireCaption}/><Figure name="wireframe02" label="Iteración 02 · apertura" caption="La navegación general se diferencia de la acción de contacto del hero. El titular coincide en los dos frames conservados."/></div>
<p className="fl-transcript">Lectura de la comparación: navegación por secciones → navegación general del sitio; acción de contacto dentro de la apertura.</p>
<Prose index={1} from={2}/><div className="fl-contrast"><Figure name="diferencial" label="El diferencial como comparación visual" caption="Representé el contraste entre información declarada y comportamiento documentado para explicar la propuesta de No Country. Es contenido de la landing diseñada, no una prueba de eficacia del modelo."/>
<div className="fl-table-wrap"><table><caption>Transcripción del contraste diseñado</caption><thead><tr><th scope="col">Enfoque tradicional</th><th scope="col">Propuesta No Country</th></tr></thead><tbody><tr><td>SE PRESENTA</td><td>SE OBSERVA</td></tr><tr><td>DECLARADO</td><td>DOCUMENTADO</td></tr><tr><td>1 HORA</td><td>SEMANAS</td></tr></tbody></table></div></div></section>
<section aria-labelledby="fl-heading-2"><div className="fl-argument"><Heading index={2}/><Prose index={2}/></div><div className="fl-pair"><Figure name="aperturaDesktop" label="Desktop · región de contenido" caption="Apertura en desktop: mantuve el énfasis en ‘evidencia real’ y la acción junto al mensaje. Se muestra la región de contenido del hero; el recurso de apoyo queda fuera de este encuadre."/><Figure name="aperturaMobile" label="Mobile · misma región" caption="La apertura mobile conserva mensaje y acción. Diseño propio con dirección de marca de No Country; se selecciona la misma región sin alterar su contenido."/></div><p className="fl-transcript"><strong>Texto de la interfaz:</strong> Talento junior con evidencia real antes de contratar. · Ver como funciona</p></section>
<section aria-labelledby="fl-heading-3"><div className="fl-argument"><Heading index={3}/><Prose index={3} to={1}/></div><div className="fl-process-comparison"><Figure name="procesoDesktop" label="Proceso · desktop" caption={processCaption}/><div className="fl-mobile-pair"><Figure name="procesoMobile01" label="Mobile · pasos 1 y 2" caption="Detalle contiguo del proceso apilado: reunión y catálogo."/><Figure name="procesoMobile02" label="Mobile · pasos 3 y 4" caption="Continuación de la misma región: entrevistas y onboarding. Los plazos interiores son contenido de la propuesta, no resultados del diseño."/></div></div><ol className="fl-transcript"><li>Reunión de hallazgo</li><li>Catálogo curado</li><li>Entrevistas coordinadas</li><li>Onboarding en 72 horas</li></ol><Prose index={3} from={1} to={2}/><div className="fl-pair"><Figure name="formularioDesktop" label="Formulario · desktop" caption={formCaption}/><Figure name="formularioMobile" label="Formulario · mobile" caption="La adaptación apila rol y fecha y conserva etiquetas, ayudas y acción. Diseño bajo mi responsabilidad; no se atribuye conexión técnica."/></div><div className="fl-transcript"><strong>Etiquetas y ayudas de la interfaz</strong><ul><li>Email de trabajo * · trabajo@empresa.com</li><li>Qué rol buscás · Frontend, Backend, UX/UI · Separá con comas si son varios</li><li>Para cuándo · Elegí una opción</li><li>Algo más que debamos saber · Stack, zona horaria u otro detalle del rol (opcional)</li><li>Enviar requerimiento · Sin compromiso. Te contactamos para armar el catálogo.</li></ul></div><Prose index={3} from={2}/></section>
<section aria-labelledby="fl-heading-4"><div className="fl-argument"><Heading index={4}/><Prose index={4}/></div><div className="fl-table-wrap"><table><caption>Comportamiento esperado · transcripción editorial del handoff</caption><thead><tr><th scope="col">Región</th><th scope="col">Desktop</th><th scope="col">Mobile / intermedio</th></tr></thead><tbody><tr><th scope="row">Proceso</th><td>Cuatro columnas en secuencia.</td><td>Pasos apilados en el mismo orden.</td></tr><tr><th scope="row">Formulario</th><td>Rol y fecha comparten fila.</td><td>Campos apilados.</td></tr><tr><th scope="row">Tablet</th><td>Reglas de contenedor y disposición.</td><td>768–1199 px especificados; sin frame independiente.</td></tr></tbody></table></div><p className="fl-caption">Documenté el comportamiento esperado del proceso y el formulario para coordinar con desarrollo. La tabla resume la especificación de diseño; no acredita ejecución en producción. <Source node="218:2">Handoff Empresas</Source></p></section>
<aside className="fl-testimony" aria-labelledby="fl-testimony-heading"><div className="fl-prose"><h2 id="fl-testimony-heading">Una mirada sobre la colaboración</h2><blockquote>{copy.testimony.map(p=><p key={p}>{p}</p>)}</blockquote><p>Leandro Buzeta · CEO de No Country · Recomendación sobre mi participación en el Fellowship.</p><p><a href="https://www.linkedin.com/in/leandrobuzeta/" target="_blank" rel="noopener noreferrer">Perfil de Leandro ↗</a> · <a href="https://www.linkedin.com/in/ivan-andrade-uxui/details/recommendations/" target="_blank" rel="noopener noreferrer">Recomendaciones en LinkedIn ↗</a></p></div></aside>
<section aria-labelledby="fl-heading-5"><div className="fl-argument"><Heading index={5}/><div className="fl-conclusion-content"><Prose index={5}/></div></div></section>
</article><div className="home-container"><CaseNavigation {...getCaseNavigation("fellowship")} /></div></main> }

